/*
 * generated by Xtext 2.10.0
 */
package org.booster2.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class Booster2UiModule extends AbstractBooster2UiModule {
}
