/*
 * generated by Xtext 2.10.0
 */
package org.booster2


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Booster2StandaloneSetup extends Booster2StandaloneSetupGenerated {

	def static void doSetup() {
		new Booster2StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
