/*
 * generated by Xtext 2.10.0
 */
package org.booster2


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class Booster2RuntimeModule extends AbstractBooster2RuntimeModule {
}
