/*
 * generated by Xtext 2.10.0
 */
package org.booster2.tests

import com.google.inject.Inject
import org.booster2.booster2.System
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(Booster2InjectorProvider)
class Booster2ParsingTest{

	@Inject
	ParseHelper<System> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			system example
		''')
		Assert.assertNotNull(result)
	}

}
